version: "3"
services:
    # nginxをリバースプロキシとして、野球ゲームをホスティング
    web-server:
        build: ./web
        ports:
            - 20080:80
            - 20443:443
        volumes:
            # nginx
            - ./web/nginx.conf:/etc/nginx/nginx.conf
            # アプリ
            - ./application/dist:/home/baseballApp/dist
        env_file:
            - ./application/.env
